const employee = [
  {
    id: 1,
    Name: "Waylon Kihn",
    Position: "Developer",
    BDay: "25 Nov, 1975",
    Email: "Waylon@gmail.com",
    Phone: "",
    Address: "Block A, Demo Park",
    Status: "Full-time",
  },
  {
    id: 2,
    Name: "John Doe",
    Position: "Manager",
    BDay: "12 May, 1980",
    Email: "johndoe@example.com",
    Phone: "",
    Address: "123 Main Street",
    Status: "Full-time",
  },
  {
    id: 3,
    Name: "Jane Smith",
    Position: "Designer",
    BDay: "8 Sep, 1988",
    Email: "janesmith@example.com",
    Phone: "",
    Address: "456 Elm Street",
    Status: "Part-time",
  },
  {
    id: 4,
    Name: "Michael Johnson",
    Position: "Analyst",
    BDay: "17 Feb, 1982",
    Email: "michaeljohnson@example.com",
    Phone: "",
    Address: "789 Oak Street",
    Status: "Full-time",
  },
  {
    id: 5,
    Name: "Emily Brown",
    Position: "Assistant",
    BDay: "3 Apr, 1990",
    Email: "emilybrown@example.com",
    Phone: "",
    Address: "101 Pine Street",
    Status: "Full-time",
  },
  {
    id: 6,
    Name: "David Lee",
    Position: "Engineer",
    BDay: "21 Jul, 1985",
    Email: "davidlee@example.com",
    Phone: "",
    Address: "202 Maple Street",
    Status: "Part-time",
  },
  {
    id: 7,
    Name: "Sarah Adams",
    Position: "Marketing",
    BDay: "9 Oct, 1978",
    Email: "sarahadams@example.com",
    Phone: "",
    Address: "303 Walnut Street",
    Status: "Full-time",
  },
  {
    id: 8,
    Name: "Chris Wilson",
    Position: "Sales",
    BDay: "14 Mar, 1987",
    Email: "chriswilson@example.com",
    Phone: "",
    Address: "404 Cedar Street",
    Status: "Part-time",
  },
  {
    id: 9,
    Name: "Olivia Taylor",
    Position: "HR",
    BDay: "29 Jun, 1984",
    Email: "oliviataylor@example.com",
    Phone: "",
    Address: "505 Birch Street",
    Status: "Full-time",
  },
  {
    id: 10,
    Name: "Daniel Martinez",
    Position: "Accountant",
    BDay: "5 Dec, 1983",
    Email: "danielmartinez@example.com",
    Phone: "",
    Address: "606 Pineapple Street",
    Status: "Full-time",
  },
  {
    id: 11,
    Name: "Ella Williams",
    Position: "Graphic Designer",
    BDay: "14 Aug, 1989",
    Email: "ellawilliams@example.com",
    Phone: "",
    Address: "707 Orange Street",
    Status: "Part-time",
  },
  {
    id: 12,
    Name: "James Brown",
    Position: "Software Engineer",
    BDay: "19 Jan, 1986",
    Email: "jamesbrown@example.com",
    Phone: "",
    Address: "808 Lemon Street",
    Status: "Full-time",
  },
  {
    id: 13,
    Name: "Sophia Clark",
    Position: "Data Analyst",
    BDay: "26 Mar, 1981",
    Email: "sophiaclark@example.com",
    Phone: "",
    Address: "909 Peach Street",
    Status: "Full-time",
  },
  {
    id: 14,
    Name: "Liam Taylor",
    Position: "Marketing Manager",
    BDay: "9 Jul, 1977",
    Email: "liamtaylor@example.com",
    Phone: "",
    Address: "1010 Grape Street",
    Status: "Full-time",
  },
  {
    id: 15,
    Name: "Ava Hernandez",
    Position: "Customer Support",
    BDay: "22 Sep, 1992",
    Email: "avahernandez@example.com",
    Phone: "",
    Address: "1111 Mango Street",
    Status: "Part-time",
  },
  {
    id: 16,
    Name: "Noah Martinez",
    Position: "Financial Analyst",
    BDay: "7 Dec, 1984",
    Email: "noahmartinez@example.com",
    Phone: "",
    Address: "1212 Kiwi Street",
    Status: "Full-time",
  },
  {
    id: 17,
    Name: "Isabella Gonzalez",
    Position: "HR Assistant",
    BDay: "30 Apr, 1991",
    Email: "isabellagonzalez@example.com",
    Phone: "",
    Address: "1313 Banana Street",
    Status: "Part-time",
  },
  {
    id: 18,
    Name: "Mason Rodriguez",
    Position: "Sales Representative",
    BDay: "15 Feb, 1988",
    Email: "masonrodriguez@example.com",
    Phone: "",
    Address: "1414 Pine Street",
    Status: "Full-time",
  },
  {
    id: 19,
    Name: "Charlotte Lee",
    Position: "Project Manager",
    BDay: "10 Jun, 1983",
    Email: "charlottee@example.com",
    Phone: "",
    Address: "1515 Oak Street",
    Status: "Full-time",
  },
  {
    id: 20,
    Name: "Lucas Martinez",
    Position: "IT Support",
    BDay: "25 Oct, 1980",
    Email: "lucasmartinez@example.com",
    Phone: "",
    Address: "1616 Elm Street",
    Status: "Part-time",
  },
  {
    id: 21,
    Name: "Amelia Johnson",
    Position: "Quality Assurance",
    BDay: "11 Mar, 1993",
    Email: "ameliajohnson@example.com",
    Phone: "",
    Address: "1717 Walnut Street",
    Status: "Full-time",
  },
  {
    id: 22,
    Name: "Ethan Thompson",
    Position: "Software Developer",
    BDay: "28 Aug, 1982",
    Email: "ethanthompson@example.com",
    Phone: "",
    Address: "1818 Maple Street",
    Status: "Full-time",
  },
  {
    id: 23,
    Name: "Harper White",
    Position: "Content Writer",
    BDay: "6 Sep, 1994",
    Email: "harperwhite@example.com",
    Phone: "",
    Address: "1919 Pine Street",
    Status: "Part-time",
  },
  {
    id: 24,
    Name: "Logan Adams",
    Position: "IT Specialist",
    BDay: "23 Nov, 1989",
    Email: "loganadams@example.com",
    Phone: "",
    Address: "2020 Oak Street",
    Status: "Full-time",
  },
  {
    id: 25,
    Name: "Avery Martinez",
    Position: "Marketing Coordinator",
    BDay: "18 Jul, 1986",
    Email: "averymartinez@example.com",
    Phone: "",
    Address: "2121 Elm Street",
    Status: "Part-time",
  },
  {
    id: 26,
    Name: "Jackson Brown",
    Position: "Financial Advisor",
    BDay: "4 May, 1981",
    Email: "jacksonbrown@example.com",
    Phone: "",
    Address: "2222 Pine Street",
    Status: "Full-time",
  },
  {
    id: 27,
    Name: "Scarlett Wilson",
    Position: "Sales Manager",
    BDay: "20 Oct, 1976",
    Email: "scarlettwilson@example.com",
    Phone: "",
    Address: "2323 Oak Street",
    Status: "Full-time",
  },
  {
    id: 28,
    Name: "Gabriel Garcia",
    Position: "HR Manager",
    BDay: "17 Apr, 1980",
    Email: "gabrielgarcia@example.com",
    Phone: "",
    Address: "2424 Elm Street",
    Status: "Full-time",
  },
  {
    id: 29,
    Name: "Madison Smith",
    Position: "Representative",
    BDay: "12 Dec, 1990",
    Email: "madisonsmith@example.com",
    Phone: "",
    Address: "2525 Pine Street",
    Status: "Part-time",
  },
  {
    id: 30,
    Name: "Elijah Taylor",
    Position: "Business Analyst",
    BDay: "27 Feb, 1984",
    Email: "elijahtaylor@example.com",
    Phone: "",
    Address: "2626 Oak Street",
    Status: "Full-time",
  },
  {
    id: 31,
    Name: "Elijah Garcia",
    Position: "Software Developer",
    BDay: "14 Apr, 1993",
    Email: "elijahgarcia@example.com",
    Phone: "",
    Address: "2727 Banana Street",
    Status: "Full-time",
  },
  {
    id: 32,
    Name: "Mia Martinez",
    Position: "Project Coordinator",
    BDay: "9 Oct, 1995",
    Email: "miamartinez@example.com",
    Phone: "",
    Address: "2828 Apple Street",
    Status: "Part-time",
  },
  {
    id: 33,
    Name: "Logan Rodriguez",
    Position: "Marketing Coordinator",
    BDay: "25 Jun, 1987",
    Email: "loganrodriguez@example.com",
    Phone: "",
    Address: "2929 Cherry Street",
    Status: "Full-time",
  },
  {
    id: 34,
    Name: "Sophia Wilson",
    Position: "Financial Analyst",
    BDay: "12 Mar, 1986",
    Email: "sophiawilson@example.com",
    Phone: "",
    Address: "3030 Grapefruit Street",
    Status: "Part-time",
  },
  {
    id: 35,
    Name: "Jackson Johnson",
    Position: "Sales Manager",
    BDay: "3 Aug, 1984",
    Email: "jacksonjohnson@example.com",
    Phone: "",
    Address: "3131 Fig Street",
    Status: "Full-time",
  },
  {
    id: 36,
    Name: "Ava Thompson",
    Position: "HR Coordinator",
    BDay: "19 Feb, 1990",
    Email: "avathompson@example.com",
    Phone: "",
    Address: "3232 Plum Street",
    Status: "Part-time",
  },
  {
    id: 37,
    Name: "Oliver Hernandez",
    Position: "Software Engineer",
    BDay: "27 Nov, 1989",
    Email: "oliverhernandez@example.com",
    Phone: "",
    Address: "3333 Avocado Street",
    Status: "Full-time",
  },
  {
    id: 38,
    Name: "Emma Nguyen",
    Position: "Customer Support Specialist",
    BDay: "8 May, 1992",
    Email: "emmanguyen@example.com",
    Phone: "",
    Address: "3434 Persimmon Street",
    Status: "Part-time",
  },
  {
    id: 39,
    Name: "William Brown",
    Position: "Data Analyst",
    BDay: "16 Jul, 1988",
    Email: "williambrown@example.com",
    Phone: "",
    Address: "3535 Papaya Street",
    Status: "Full-time",
  },
  {
    id: 40,
    Name: "Charlotte Garcia",
    Position: "Marketing Specialist",
    BDay: "21 Oct, 1983",
    Email: "charlottegarcia@example.com",
    Phone: "",
    Address: "3636 Pineapple Street",
    Status: "Part-time",
  },
];

export default employee;
